'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ELITE_GI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1485791411_caution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1485791411_caution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BLADRMF_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BLADRMF_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite-background-GI-111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_190() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_190", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_214() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_214", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite-background-GI-51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite-background-GI-511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_background_GI_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_background_GI_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_banner_GI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_banner_GI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_fvi_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_fvi_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_fvi_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_fvi_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_fvi_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_fvi_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_injection_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_injection_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_injection_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_injection_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_mounter_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_mounter_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_mounter_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_mounter_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_epson_background_mounter_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_epson_background_mounter_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property elite_gi_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elite_gi_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emscai_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emscai_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Graphicloads_100_Flat_Unlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Graphicloads_100_Flat_Unlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngegg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngegg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngegg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngegg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property replac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scan_completed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scan_completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_BoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_Italic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Italic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_Light() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Light", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_LightItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_LightItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_Medium() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Medium", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_MediumItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_MediumItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ubuntu_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
